### ISSUE TITLE
Problem with code execution (Syntax Error)

### ISSUE THREAD

**Issue by samuelmorais** [mitmadness/AssetBundleCompiler#4]
Hello,
I really think your solution to AssetBundle generation is going to help me in my current project, but I can't make it work.
My problem is that, in Mac High Sierra 10.13.3 with Node  v9.10.1, I have installed brew and, when I try to use AssetBundleCompiler, I do the following:
1) I cloned the repository to a folder;
2) Ran npm install in that folder;
3) Created a file named test.js and pasted the [sample code](https://github.com/mitmadness/AssetBundleCompiler#link-simple-fluent-api)  to it.
4) Ran >  node test.js
test.js:1
(function (exports, require, module, __filename, __dirname) { import { BuildTargets, bundle } from '@mitm/assetbundlecompiler';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)

Question: What am I doing wrong? Is this the right way of running your code? I am very unfamiliar with all this stuff (npm, node etc), so if you can explain it more didactically I would appreciate. Thank you very much in advance!

**Comment by samuelmorais** [comment]
After some research I have found out that this code was written in typescript and it needed some adjustments to run it with node.js.
After doing that, I am still having some issues regarding file reading:

sudo node dist/abc.js
Preparing Unity project in /tmp/AssetBundleCompiler
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read


Here is my code: 


```
import { BuildTargets, bundle } from "@mitm/assetbundlecompiler";

const { WebGL } = BuildTargets;


(async () => {
    // code goes here
    // bundle() is the entry function to the API.
// Pass a list of assets to bundle into the resulting asset bundle.
// Those assets could be anywhere on the filesystem.
// To pass an array of paths, use bundle(...paths) syntax.
await bundle("/Users/samuelmorais/Documents/abc/fbx", "/Users/samuelmorais/Documents/abc/texture", /* ... */)
// .targeting() is mandatory and tells the library what platform your asset bundle targets.
// You can either pass a predefined constant in BuildTargets, or a string,
// matching the name of a member of the UnityEditor.BuildTarget enum.
// @see https://docs.unity3d.com/ScriptReference/BuildTarget.html
.targeting(WebGL)

// Lets you install custom Editor scripts before asset bundle generation.
// This is very useful, for example, to create an Asset Postprocessor to customize how
// your resources are imported into the asset bundle, using AssetImporters for example.
// @see https://docs.unity3d.com/ScriptReference/AssetPostprocessor.html
// .includingEditorScripts("/abs/path/to/script.dll", "/abs/path/to/script.cs")

// Lets you define build options. Those are always flags, and the key names represent
// member names of the UnityEditor.BuildAssetBundleOptions enum.
// @see https://docs.unity3d.com/ScriptReference/BuildAssetBundleOptions.html
.withBuildOptions({ chunkBasedCompression: true, strictMode: true, /* etc */ })

// This lets you define a simple logger to get simple text updates about the conversion.
.withLogger(message => console.log(message))

// This lets you define a logger for the real-time output of Unity (stdout+stderr).
// Beware, it's very verbose :)
.withUnityLogger(message => console.log(`Unity: ${message}`))

// This is the "run" function and marks the termination of the fluent calls
// by returning a Promise that resolves when the asset bundle generation ends.
// Give it a path to the asset bundle name or a fs.WriteStream.
.to("/Users/samuelmorais/Documents/abc/resources.assetbundle");
})();

```

**Comment by samuelmorais** [comment]
Hi, after some research I found that was my mistake.
The problem was in this line:
`await bundle("/Users/samuelmorais/Documents/abc/fbx", "/Users/samuelmorais/Documents/abc/texture", /* ... */)`
Because I needed a file instead of directories.
So, the correct line would be:
`await bundle("/Users/samuelmorais/Documents/abc/fbx/some_file.fbx", "/Users/samuelmorais/Documents/abc/texture/some_file.png", /* ... */)`
